### ISSUE TITLE
[dataset-provider] datacore의 kafka 연동 시 Unexpected handshake request with client mechanism PLAIN 에러 발생

### ISSUE THREAD

**Issue by vanilet** [IoTKETI/citydatahub_data_marketplace_module#1]
에러메시지는 아래와 같음

1. datahub-datservice-dataset-provider 모듈의 dataset provider 로그
`
2022-11-25 15:22:27.027 ERROR [APP_NAME_IS_UNDEFINED,,] 11839 --- [kafka-producer-network-thread | DemoProducer] org.apache.kafka.clients.NetworkClient - [Producer clientId=DemoProducer] Connection to node -1 (10.0.0.70/10.0.0.70:9092) failed authentication due to: Unexpected handshake request with client mechanism PLAIN, enabled mechanisms are []
`
2. 동일 모듈의 설정파일(application-env.yml)
```YAML
spring.profiles: test
spring:
  datasource:
    url: jdbc:postgresql://10.0.0.23:5432/data
    username: smartcity_data
    password: dpsxndpa
    hikari:
      maximum-pool-size: 400
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB

  kafka:
    bootstrap-servers: 10.0.0.70:9092
    auth:
      user_id: dataservice
      user_pw: dataservice!123

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://10.0.0.112:8888/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    ip-address: 10.0.0.112

smartcity:
  # smartcity datacore - data service broker 서버URL
  datacore:
    server: http://10.0.0.70:8082
  # smartcity datacore - data manager 서버URL
  datamanager:
    server: http://10.0.0.70:8080
  # 인증인가서버(사용자용 서버) URL
  auth:
    server: http://10.0.0.231:30000
  # 현재 모듈(dataset-provider) 의 외부접속 가능한 공개IP주소 (data service broker 서버로부터 subscription 의 데이터 수신(HTTP통신) 받기위함)
  dataset-provider-public-ip : 172.20.0.174:7930

file:
  # 첨부파일 저장경로
  upload-path: /opt/smartcity
```
